[package]
name = "brc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr = "2.7.2"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "debuginfo"